BuilderWebSite/Areas/Admin/Controllers/Abstract/AdminBaseController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BuilderWebSite.Areas.Admin.Controllers.Abstract
{
    public class AdminBaseController : Controller
    {
        public string RenderPartialViewToString(string viewName, object model)
        {
            if (string.IsNullOrEmpty(viewName))
                viewName = ControllerContext.RouteData.GetRequiredString("action");

            ViewData.Model = model;

            using (var sw = new StringWriter())
            {
                var viewResult = ViewEngines.Engines.FindPartialView(ControllerContext, viewName);
                var viewContext = new ViewContext(ControllerContext, viewResult.View, ViewData, TempData, sw);
                viewResult.View.Render(viewContext, sw);

                return sw.GetStringBuilder().ToString();
            }
        }
    }
}

BuilderWebSite/Areas/Admin/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BuilderWebSite.Areas.Admin.Controllers
{
    public class HomeController : Controller
    {
        // GET: Admin/Home
        public ActionResult Index()
        {
            return View();
        }
    }
}

BuilderWebSite/Areas/Admin/Controllers/LoginController.cs
using BuilderWebSite.Services.Admin;
using BuilderWebSite.ViewModels.Admin;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace BuilderWebSite.Areas.Admin.Controllers
{
    public class LoginController : Controller
    {
        private LoginService _loginservice;

        public LoginController(LoginService loginService)
        {
            _loginservice = loginService;
        }

        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Index(LoginViewModel model)
        {
            if (ModelState.IsValid)
            {
                var loginResult = _loginservice.Login(model);
                if (loginResult)
                {
                    FormsAuthentication.SetAuthCookie(model.Id.ToString(), false);
                    return RedirectToAction("Index", "Home", new { Area = "Admin" });
                }
            }
            return View(model);
        }
    }
}

BuilderWebSite/Controllers/AboutController.cs
using BuilderWebSite.Services.WebSite;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BuilderWebSite.Controllers
{
    public class AboutController : Controller
    {
        private readonly AboutService _aboutService;

        public AboutController(AboutService aboutService)
        {
            _aboutService = aboutService;
        }

        // GET: About
        public ActionResult Index()
        {
            var model = _aboutService.GetAboutViewModel();
            return View(model);
        }
    }
}

BuilderWebSite/Controllers/BaseController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BuilderWebSite.Controllers
{
    public class BaseController : Controller
    {
        // GET: Base
        public string RenderPartialViewToString(string viewName, object model)
        {
            if (string.IsNullOrEmpty(viewName))
                viewName = ControllerContext.RouteData.GetRequiredString("action");

            ViewData.Model = model;

            using (var sw = new StringWriter())
            {
                var viewResult = ViewEngines.Engines.FindPartialView(ControllerContext, viewName);
                var viewContext = new ViewContext(ControllerContext, viewResult.View, ViewData, TempData, sw);
                viewResult.View.Render(viewContext, sw);

                return sw.GetStringBuilder().ToString();
            }
        }
    }
}

BuilderWebSite/Controllers/ContactController.cs
using BuilderWebSite.Services.WebSite;
using BuilderWebSite.ViewModels.WebSite;
using System.Web.Mvc;

namespace BuilderWebSite.Controllers
{
    public class ContactController : BaseController
    {
        private readonly ContactService _contactService;

        public ContactController(ContactService contactService)
        {
            _contactService = contactService;
        }

        public ActionResult Index(string lang)
        {
            return View();
        }

        [HttpPost]
        public ActionResult Index(ContactViewModel model)
        {
            var result = _contactService.AddContactForm(model);
            return Json(new { item = "başarılı" }, JsonRequestBehavior.AllowGet);
        }
    }
}

BuilderWebSite/Controllers/HomeController.cs
using BuilderWebSite.Services.WebSite;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BuilderWebSite.Controllers
{
    public class HomeController : BaseController
    {
        private readonly SliderService _sliderService;
        private readonly OurService _ourService;
        private readonly ContactUsService _contactUsService;
        private readonly RecentProjectsService _recentProjectsService;
        private readonly ReferencesService _referencesService;

        public HomeController(
            SliderService sliderService,
            OurService ourServices,
            ContactUsService contactUsService,
            RecentProjectsService recentProjectsService,
            ReferencesService referencesService
            )
        {
            _sliderService = sliderService;
            _ourService = ourServices;
            _contactUsService = contactUsService;
            _recentProjectsService = recentProjectsService;
            _referencesService = referencesService;
        }

        public ActionResult Index()
        {
            return View();
        }
        public ActionResult SliderPartial()
        {
            var model = _sliderService.GetSliderListIQueryable().ToList();
            return PartialView("~/Views/Home/SliderPartial.cshtml", model);

        }
        public ActionResult OurServices()
        {
            var model = _ourService.GetOurServicesListIQueryable().ToList();
            return PartialView("~/Views/Home/OurServicesPartial.cshtml", model);

        }
        public ActionResult ContactUs()
        {
            var model = _contactUsService.GetContactIQueryable().FirstOrDefault();
            return PartialView("~/Views/Home/ContactUsPartial.cshtml", model);

        }
        public ActionResult RecentProjects()
        {
            var model = _recentProjectsService.GetRecentProjectsListIQueryable().ToList();
            return PartialView("~/Views/Home/RecentProjectsPartial.cshtml", model);

        }
        public ActionResult References()
        {
            var model = _referencesService.GetReferencesListIQueryable().ToList();
            return PartialView("~/Views/Home/ReferencesPartial.cshtml", model);
        }
    }
}

BuilderWebSite/Controllers/OurServiceController.cs
using BuilderWebSite.Services.WebSite;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BuilderWebSite.Controllers
{
    public class OurServiceController : BaseController
    {
        private readonly OurService _ourService;

        public OurServiceController(
            OurService ourServices
            )
        {
            _ourService = ourServices;
        }

        // GET: OurService
        public ActionResult Index()
        {
            var model = _ourService.GetOurServicesListIQueryable().ToList();
            return View(model);
        } public ActionResult ServiceDetail(int id)
        {
            var model = _ourService.GetOurServiceDetail(id);
            return View(model);
        }
    }
}

BuilderWebSite/Controllers/RecentProjectsController.cs
using BuilderWebSite.Services.WebSite;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BuilderWebSite.Controllers
{
    public class RecentProjectsController : BaseController
    {
        private readonly RecentProjectsService _recentProjectsService;

        public RecentProjectsController(RecentProjectsService recentProjectsService)
        {
            _recentProjectsService = recentProjectsService;
        }
        // GET: RecentProjects
        public ActionResult Index()
        {
            var model = _recentProjectsService.GetRecentProjectsListIQueryable().ToList();
            return View(model);
        }
    }
}

BuilderWebSite/Areas/Admin/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h2>admin areas</h2>

BuilderWebSite/Areas/Admin/Views/Login/Index.cshtml
@model BuilderWebSite.ViewModels.Admin.LoginViewModel

@{
    Layout = null;
}
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
<!------ Include the above in your HEAD tag ---------->
<style>
    body {
        margin: 0;
        color: #edf3ff;
        background: #c8c8c8;
        background: url(https://hdqwalls.com/download/material-design-4k-2048x1152.jpg) fixed;
        background-size: cover;
        font: 600 16px/18px 'Open Sans',sans-serif;
    }

    :after, :before {
        box-sizing: border-box
    }

    .clearfix:after, .clearfix:before {
        content: '';
        display: table
    }

    .clearfix:after {
        clear: both;
        display: block
    }

    a {
        color: inherit;
        text-decoration: none
    }

    .login-wrap {
        width: 100%;
        margin: auto;
        max-width: 510px;
        min-height: 510px;
        position: relative;
        background: url(https://maxcdn.icons8.com/app/uploads/2016/03/material-1-1000x563.jpg) no-repeat center;
        background-size: cover;
        box-shadow: 0 12px 15px 0 rgba(0,0,0,.24),0 17px 50px 0 rgba(0,0,0,.19);
    }

    .login-html {
        width: 100%;
        height: 100%;
        position: absolute;
        padding: 90px 70px 50px 70px;
        background: rgba(0,0,0,0.5);
    }

        .login-html .sign-in-htm,
        .login-html .for-pwd-htm {
            top: 0;
            left: 0;
            right: 0;
            bottom: 0;
            position: absolute;
            -webkit-transform: rotateY(180deg);
            transform: rotateY(180deg);
            -webkit-backface-visibility: hidden;
            backface-visibility: hidden;
            -webkit-transition: all .4s linear;
            transition: all .4s linear;
        }

        .login-html .sign-in,
        .login-html .for-pwd,
        .login-form .group .check {
            display: none;
        }

        .login-html .tab,
        .login-form .group .label,
        .login-form .group .button {
            text-transform: uppercase;
        }

        .login-html .tab {
            font-size: 22px;
            margin-right: 15px;
            padding-bottom: 5px;
            margin: 0 15px 10px 0;
            display: inline-block;
            border-bottom: 2px solid transparent;
        }

        .login-html .sign-in:checked + .tab,
        .login-html .for-pwd:checked + .tab {
            color: #fff;
            border-color: #1161ee;
        }

    .login-form {
        min-height: 345px;
        position: relative;
        -webkit-perspective: 1000px;
        perspective: 1000px;
        -webkit-transform-style: preserve-3d;
        transform-style: preserve-3d;
    }

        .login-form .group {
            margin-bottom: 15px;
        }

            .login-form .group .label,
            .login-form .group .input,
            .login-form .group .button {
                width: 100%;
                color: #fff;
                display: block;
            }

            .login-form .group .input,
            .login-form .group .button {
                border: none;
                padding: 15px 20px;
                border-radius: 25px;
                background: rgba(255,255,255,.1);
            }

            .login-form .group input[data-type="password"] {
                text-security: circle;
                -webkit-text-security: circle;
            }

            .login-form .group .label {
                color: #aaa;
                font-size: 12px;
            }

            .login-form .group .button {
                background: #1161ee;
            }

            .login-form .group label .icon {
                width: 15px;
                height: 15px;
                border-radius: 2px;
                position: relative;
                display: inline-block;
                background: rgba(255,255,255,.1);
            }

                .login-form .group label .icon:before,
                .login-form .group label .icon:after {
                    content: '';
                    width: 10px;
                    height: 2px;
                    background: #fff;
                    position: absolute;
                    -webkit-transition: all .2s ease-in-out 0s;
                    transition: all .2s ease-in-out 0s;
                }

                .login-form .group label .icon:before {
                    left: 3px;
                    width: 5px;
                    bottom: 6px;
                    -webkit-transform: scale(0) rotate(0);
                    transform: scale(0) rotate(0);
                }

                .login-form .group label .icon:after {
                    top: 6px;
                    right: 0;
                    -webkit-transform: scale(0) rotate(0);
                    transform: scale(0) rotate(0);
                }

            .login-form .group .check:checked + label {
                color: #fff;
            }

                .login-form .group .check:checked + label .icon {
                    background: #1161ee;
                }

                    .login-form .group .check:checked + label .icon:before {
                        -webkit-transform: scale(1) rotate(45deg);
                        transform: scale(1) rotate(45deg);
                    }

                    .login-form .group .check:checked + label .icon:after {
                        -webkit-transform: scale(1) rotate(-45deg);
                        transform: scale(1) rotate(-45deg);
                    }

    .login-html .sign-in:checked + .tab + .for-pwd + .tab + .login-form .sign-in-htm {
        -webkit-transform: rotate(0);
        transform: rotate(0);
    }

    .login-html .for-pwd:checked + .tab + .login-form .for-pwd-htm {
        -webkit-transform: rotate(0);
        transform: rotate(0);
    }

    .hr {
        height: 2px;
        margin: 60px 0 50px 0;
        background: rgba(255,255,255,.2);
    }

    .foot-lnk {
        text-align: center;
    }
</style>
<div class="login-wrap">
    <div class="login-html">
        @using (Html.BeginForm("Index", "Login", new { Area = String.Empty }, FormMethod.Post, new { id = "loginForm", role = "form" }))
        {
            <div class="login-form">
                <div class="group">
                    <label class="label">
                        @Html.DisplayNameFor(a => a.UserName)
                    </label>
                    @Html.TextBoxFor(a => a.UserName, new { type = "text", @class = "input" })
                </div>
                <div class="group">
                    <label class="label">
                        @Html.DisplayNameFor(a => a.Password)
                    </label>
                    @Html.TextBoxFor(a => a.Password, new { type = "password", @class = "input", data_type = "password" })
                </div>
                <div class="group">
                    <input type="submit" class="button" value="Giriş">
                </div>
                <div class="hr"></div>
            </div>
        }
    </div>
</div>

BuilderWebSite/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Admin</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Bootstrap 3.3.7 -->
    <link href="~/Areas/Admin/Content/bootstrap.min.css" rel="stylesheet" />
    <!-- Font Awesome -->
    <link href="~/Areas/Admin/Content/font-awesome.css" rel="stylesheet" />
    <!-- Ionicons -->
    <link href="~/Areas/Admin/Content/toastr.css" rel="stylesheet" />
    <!-- Theme style -->
    <link href="~/Areas/Admin/Content/switchery.min.css" rel="stylesheet" />
    <link href="~/Areas/Admin/Content/admin-lte/css/AdminLTE.min.css" rel="stylesheet" />
    <!-- AdminLTE Skins. Choose a skin from the css/skins
         folder instead of downloading all of them to reduce the load. -->
    <link href="~/Areas/Admin/Content/admin-lte/css/skins/_all-skins.css" rel="stylesheet" />
    <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-tagsinput/0.8.0/bootstrap-tagsinput.css" rel="stylesheet" />
    <script src="~/Areas/Admin/Scripts/jquery-3.1.1.min.js"></script>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <!-- Google Font -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
</head>
<body class="hold-transition skin-green sidebar-mini">
    <!-- Site wrapper -->
    <div class="wrapper">

        <header class="main-header">
            <!-- Logo -->
            <a href="@Url.Action("Index","Home")" class="logo">
                <!-- mini logo for sidebar mini 50x50 pixels -->
                <!-- logo for regular state and mobile devices -->
                <span class="logo-lg"><b>Admin</b></span>
            </a>
            <!-- Header Navbar: style can be found in header.less -->
            <nav class="navbar navbar-static-top">
                <!-- Sidebar toggle button-->
                <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </a>
                <div class="navbar-custom-menu">
                </div>
            </nav>
        </header>

        <!-- =============================================== -->
        <!-- Left side column. contains the sidebar -->
        <aside class="main-sidebar">
            <!-- sidebar: style can be found in sidebar.less -->
            <section class="sidebar">
                <!-- Sidebar user panel -->
                <!-- search form -->
                <!-- /.search form -->
                <!-- sidebar menu: : style can be found in sidebar.less -->
                <ul class="sidebar-menu" data-widget="tree">
                    <li><a href="@Url.Action("Index","Home",new {Area="Admin"})"><i class="fa fa-keyboard-o"></i> <span>Ana Sayfa</span></a></li>
                </ul>
            </section>
            <!-- /.sidebar -->
        </aside>

        <!-- =============================================== -->
        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            <!-- Content Header (Page header) -->
            <section class="content">
                @RenderBody()
            </section>
            <!-- /.content -->
        </div>
        <!-- /.content-wrapper -->

        <footer class="main-footer">
            <strong>Copyright @DateTime.Today.Year </strong>
        </footer>

        <!-- Control Sidebar -->
        <!-- /.control-sidebar -->
        <!-- Add the sidebar's background. This div must be placed
             immediately after the control sidebar -->
        <div class="control-sidebar-bg"></div>
    </div>
    <!-- ./wrapper -->
    <!-- jQuery 3 -->
    <!-- Bootstrap 3.3.7 -->
    <script src="~/Areas/Admin/Scripts/bootstrap.min.js"></script>
    <script src="~/Areas/Admin/Scripts/bootstrap-maxlength/bootstrap-maxlength.min.js"></script>
    <script src="~/Areas/Admin/Scripts/bootstrap-confirmation/bootstrap-confirmation.js"></script>

    <!-- SlimScroll -->
    <!-- FastClick -->
    @*<script src="../../bower_components/fastclick/lib/fastclick.js"></script>*@
    <!-- AdminLTE App -->
    <script src="~/Areas/Admin/Content/admin-lte/js/adminlte.min.js"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/1.20.3/TweenMax.min.js"></script>

    <script src="~/Areas/Admin/Content/admin-lte/js/demo.js"></script>
    <script src="~/Areas/Admin/Scripts/custom.ajax.form.js"></script>
    <script src="~/Areas/Admin/Scripts/custom.modal.form.js"></script>
    <script src="~/Areas/Admin/Scripts/custom.ajax.pager.js"></script>
    <script src="~/Areas/Admin/Scripts/toastr.js"></script>
    <script src="~/Areas/Admin/Scripts/switchery.min.js"></script>
    <script src="~/Areas/Admin/Scripts/site.js"></script>
    <script src="~/Areas/Admin/Scripts/jquery.validate.min.js"></script>
    <script src="~/Areas/Admin/Scripts/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/Scripts/ckeditor/ckeditor.js"></script>
</body>
</html>

BuilderWebSite/Views/About/Index.cshtml
@model BuilderWebSite.ViewModels.WebSite.AboutViewModel
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div id="page-heading">
    <div class="container">
        <div class="row">

        </div>
    </div>
</div>

<section class="expert-field">
    <div class="container">
        <div class="row">
            <div class="col-md-5">
                <div class="left-image">
                    <img src="@Model.FileName" alt="">
                </div>
            </div>
            <div class="col-md-7">
                <div class="expert-content">
                    <h4>@Model.Title</h4>
                    <div class="line-dec"></div>
                    <p>@Model.Description</p>
                </div>
            </div>
        </div>
    </div>
</section>

BuilderWebSite/Views/Contact/Index.cshtml
@model BuilderWebSite.ViewModels.WebSite.ContactViewModel
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div id="page-heading">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h1 style="color:black">Bize Ulaşın</h1>
            </div>
        </div>
    </div>
</div>
@using (Html.BeginForm("Index", "Contact", FormMethod.Post))
{
    <section class="contact-form">
        <div class="container">
            <div class="row">
                <div class="col-md-8">
                    <div class="contact-form">
                        <form id="contact_form" action="#" method="POST" enctype="multipart/form-data">
                            <div class="row">
                                <div class="col-md-12">
                                    @Html.TextBoxFor(m => m.FullName, new { @class = "name", placeholder = "Ad Soyad" })
                                </div>
                                <div class="col-md-12">
                                    @Html.TextBoxFor(m => m.Email, new { @class = "email", placeholder = "Email" })
                                </div>
                                <div class="col-md-12">
                                    @Html.TextAreaFor(m => m.Message, new { @class = "message", placeholder = "Mesajınızı Yazın" })

                                </div>
                                <div class="col-md-12">
                                    <div class="accent-button">
                                        <button type="submit">GÖNDER</button>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>

            </div>
        </div>
    </section>
}

BuilderWebSite/Views/Home/ContactUs.cshtml
<div id="cta-2">
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-1">
                <h1>Ofis Yenileme ve İç Dekorasyon Tasarım, Uygulama Projeleri</h1>
                <ul>
                    
                    <li>Dekorasyon hizmetlerine en iyisini en uygun fiyatlarla en iyi ustalarla elde edin.</li>
                </ul>
                <div class="buttons">
                    <div class="border-accent-button contact">
                        <a href="#">Bugün Başlayın</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

BuilderWebSite/Views/Home/ContactUsPartial.cshtml
@model BuilderWebSite.ViewModels.WebSite.ContactUsViewModel

<div id="cta-2">
    <div class="container">
        <div class="row">
            <div class="section-heading">
                <h2 style="color:white">Bize Ulaşın</h2>
                <div class="line-dec"></div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-8 col-md-offset-1">
                <h1>@Model.Title</h1>
                <ul>
                    <li style="font-size:1.2rem">@Model.Description</li>
                </ul>
                <div class="buttons">
                    <div class="border-accent-button contact">
                        <a href="#">@Model.ButtonText</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

}

BuilderWebSite/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@{ Html.RenderAction("SliderPartial", "Home");}

@{ Html.RenderAction("OurServices", "Home");}

@{ Html.RenderAction("ContactUs", "Home");}
<br />
@{ Html.RenderAction("RecentProjects", "Home");}

@{ Html.RenderAction("References", "Home");}

BuilderWebSite/Views/Home/OurServicesPartial.cshtml
@model List<BuilderWebSite.ViewModels.WebSite.OurServiceViewModel>

<section class="latest-news">
    <div class="container">
        <div class="row">
            <div class="section-heading col-md-12">
                <h2>Hizmetlerimiz</h2>
                <div class="line-dec"></div>
            </div>
        </div>
        <div class="row">
            @foreach (var item in Model)
            {
                <div class="col-md-4">
                    <div class="latest-item">
                        <img src="@item.FileName" alt="">
                        <div class="down-content">
                            <a href="single-blog.html"><h4>@item.Title</h4></a>
                            <p class="limit" style="white-space: pre-wrap">@item.Description</p>
                        </div>
                    </div>
                </div>}
        </div>
    </div>
</section>

BuilderWebSite/Views/Home/ReferencesPartial.cshtml
@model List<BuilderWebSite.ViewModels.WebSite.ReferencesViewModel>

<section class="clients">
    <div class="container">
        <div class="row">
            <div class="section-heading">
                <h2>REFERANSLAR</h2>
                <div class="line-dec"></div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div id="owl-clients">
                    @foreach (var item in Model)
                    {
                        <div class="item">
                            <img src="@item.FileName" alt="">
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</section>

BuilderWebSite/Views/OurService/Index.cshtml
@model List<BuilderWebSite.ViewModels.WebSite.OurServiceViewModel>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div id="page-heading">
    <div class="container">
        <div class="row">
            <div>
                <h2>Hizmetlerimiz</h2>
            </div>
        </div>
    </div>
</div>
<section class="services">
    <div class="container">
        <div class="row">
            @foreach (var item in Model)
            {
                <div class="col-md-4">
                    <div class="service-item">
                        <a href="@Url.Action("ServiceDetail","OurService", new {id=item.Id})">
                            <img src="@item.FileName" />
                        </a>
                        <a href="@Url.Action("ServiceDetail","OurService", new {id=item.Id})">
                            <h4>@item.Title</h4>
                        </a>
                        <p class="limit">@item.Description</p>
                    </div>
                </div>
            }
        </div>
    </div>
</section>

BuilderWebSite/Views/Shared/_Header.cshtml
<div id="sub-header">
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <div class="left-info">
                    <ul>
                        <li><i class="fa fa-phone"></i>05555555555</li>
                        <li><i class="fa fa-envelope-o"></i>ekrem3792@gmail.com</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
<header class="site-header">
    <div id="main-header" class="main-header header-sticky">
        <div class="inner-header container clearfix">
            <div class="logo">
                <a href="index.html"><img src="assets/images/logo.png" alt=""></a>
            </div>
            <div class="header-right-toggle pull-right hidden-md hidden-lg">
                <a href="javascript:void(0)" class="side-menu-button"><i class="fa fa-bars"></i></a>
            </div>
            <nav class="main-navigation text-right hidden-xs hidden-sm">
                <ul>
                    <li>
                        <a href="@Url.Action("Index", "Home")" class="has-submenu">AnaSayfa</a>
                    </li>
                    <li>
                        <a href="@Url.Action("Index", "About")" class="has-submenu">Hakkımızda</a>
                    </li>
                    <li>
                        <a href="@Url.Action("Index", "OurService")" class="has-submenu">Hizmetlerimiz</a>
                    </li>
                    <li>
                        <a href="@Url.Action("Index", "RecentProjects")" class="has-submenu">Projelerimiz</a>
                    </li>
                    <li>
                        <a href="@Url.Action("Index", "Contact")" class="has-submenu">İletişim</a>
                    </li>
                </ul>
            </nav>
        </div>
    </div>
</header>